# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qt-creator

# >> macros
# << macros

Summary:    Cross-platform IDE for Qt
Version:    3.1.2
Release:    1
Group:      Development/Tools
License:    LGPLv2 with exceptions
URL:        http://qt.digia.com/Product/Qt-Core-Features-Functions/Developer-Tools/
Source0:    %{name}-%{version}.tar.xz
Source100:  qt-creator.yaml
Source101:  qt-creator-rpmlintrc
Requires:   xdg-utils
Requires:   qt5-qtbase-devel
Requires:   gcc-c++
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  diffutils
BuildRequires:  desktop-file-utils

%description
Qt Creator is a cross-platform IDE (integrated development environment)
tailored to the needs of Qt developers.


%package doc
Summary:    User documentation for %{name}
Group:      Documentation
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description doc
User documentation for %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
export QTDIR=/usr/share/qt5
qmake -qt=5 -r IDE_LIBRARY_BASENAME=%{_lib} #USE_SYSTEM_BOTAN=1
# << build pre



# >> build post
make %{?_smp_mflags}
make qch_docs %{?_smp_mflags}
# << build post

%install
rm -rf %{buildroot}
# >> install pre
make install INSTALL_ROOT=%{buildroot}/%{_prefix}
make install_inst_qch_docs INSTALL_ROOT=%{buildroot}/%{_prefix}
# << install pre

# >> install post
for i in 16 24 32 48 64 128 256; do
mkdir -p %{buildroot}/%{_datadir}/icons/hicolor/${i}x${i}/apps
done
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%doc README LICENSE.LGPL LGPL_EXCEPTION.TXT
%exclude %{_defaultdocdir}/%{name}/qtcreator.qch
%{_bindir}/qbs*
%{_bindir}/buildoutputparser
%{_bindir}/qml2puppet
%{_bindir}/qtpromaker
%{_bindir}/qtcreator
%{_bindir}/qtcreator_process_stub
%{_bindir}/sdktool
%{_libdir}/qtcreator
%{_datadir}/applications/qtcreator.desktop
%{_datadir}/icons/hicolor/*/apps/QtProject-qtcreator.png
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%doc %{_defaultdocdir}/%{name}/qtcreator.qch
# >> files doc
# << files doc
